name: Webgoat                                 # workflow name

on:
  push:
    branches:                                 # similar to "only" in GitLab
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - run: echo "This is a build step"

  test:
    runs-on: ubuntu-22.04
    needs: build
    steps:
      - run: echo "This is a test step"

  odc-backend:
    runs-on: ubuntu-22.04
    name: depecheck_test
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Depcheck
        uses: dependency-check/Dependency-Check_Action@main
        id: Depcheck
        with:
          project: 'webgoat'
          path: '.'
          format: 'JSON'

      - name: Upload Test results
        uses: actions/upload-artifact@master
        with:
           name: Depcheck report
           path: ${{github.workspace}}/reports
