name: Webgoat                                 # workflow name

on:
  push:
    branches:                                 # similar to "only" in GitLab
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - run: echo "This is a build step"

  test:
    runs-on: ubuntu-22.04
    needs: build
    steps:
      - run: echo "This is a test step"
